# Generated by Django 2.2.5 on 2020-05-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('defination', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=10000)),
            ],
        ),
    ]
