# Generated by Django 2.2.5 on 2020-07-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wikipedia_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='defination',
            field=models.CharField(max_length=2000),
        ),
    ]
